name: Publish Java library snapshot
on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      java-version:
        required: true
        type: string
      java-distribution:
        required: false
        type: string
        default: temurin
    secrets:
      MAVEN_CENTRAL_PORTAL_USERNAME:
        required: false
      MAVEN_CENTRAL_PORTAL_PASSWORD:
        required: false
jobs:
  publish-to-maven-central-portal-snapshot:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          server-id: central-portal-snapshots
          server-username: MAVEN_CENTRAL_PORTAL_USERNAME
          server-password: MAVEN_CENTRAL_PORTAL_PASSWORD

      - name: Run mvn verify
        working-directory: ${{ inputs.context }}
        run: mvn verify

      - name: Run mvn deploy
        if: github.event_name != 'pull_request'
        working-directory: ${{ inputs.context }}
        env:
          MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}
          MAVEN_CENTRAL_PORTAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}
        run: mvn deploy
